### ISSUE TITLE
TCTL Updates

### ISSUE THREAD

**Issue by sabaronett** [dtamayo/reboundx#64]
## Tasks
- [x] 46561620ce65fbaee18ebb8011e7cc5340d660c7 c6d536e8f557b5f5d29c51c91d685dd9f783f949 Fix `tctl_tau` value and update plots in [`ipython_examples/TidesConstantTimeLag.ipynb`](https://github.com/dtamayo/reboundx/blob/master/ipython_examples/TidesConstantTimeLag.ipynb) and [`examples/tides_constant_time_lag/problem.c`](https://github.com/dtamayo/reboundx/blob/master/examples/tides_constant_time_lag/problem.c).
- [x] 246b2d2a94af6262dc32833b0bbe787aab7314b1 c6d536e8f557b5f5d29c51c91d685dd9f783f949 Change all instances of `k1` and `tctl_k1` to `k2` and `tctl_k2` in [`src/*`](https://github.com/dtamayo/reboundx/blob/master/src/) to match §3.1 of [Baronett et al. (2021)](https://arxiv.org/abs/2101.12277) and avoid confusion in Python example.
- [ ] Specify radius cutoff parameter to include tides between particles.

**Comment by dtamayo** [comment]
Closing this now, thanks @sabaronett !
